// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using POS_ASP_ORA.Data;

#nullable disable

namespace POS_ASP_ORA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303032707_AddIncome")]
    partial class AddIncome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS_ASP_ORA.Models.BeginingBalance", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("BalanceDate")
                        .HasColumnType("DATE")
                        .HasColumnName("BALANCE_DATE");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REMARK");

                    b.Property<decimal>("ToAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOACCOUNTID");

                    b.Property<decimal>("UserAccessId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("BEGININGBALANCE_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.CashTransfer", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("AMOUNT");

                    b.Property<decimal>("FromAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("FROMACCOUNTID");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REMARK");

                    b.Property<decimal>("ToAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOACCOUNTID");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("TRANSFERDATE");

                    b.Property<decimal>("UserAccessId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("CASHTRANSFER_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Category", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORYNAME");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("CATEGORY_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Company", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COMPANYNAME");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("REMARK");

                    b.HasKey("Id");

                    b.ToTable("COMPANY_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.CustomerCheckin", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CheckinDate");

                    b.Property<decimal>("CustomerId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CustomerId");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("CustomerCheckin_tbl");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Group", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("CompanyId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("COMPANYID");

                    b.Property<string>("GroundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("GROUPNAME");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("REMARK");

                    b.HasKey("Id");

                    b.ToTable("GROUND_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Income", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("ComeDate")
                        .HasColumnType("DATE")
                        .HasColumnName("COMEDATE");

                    b.Property<decimal>("IncomeTypeId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("INCOMETYPEID");

                    b.Property<decimal>("PaymentMethodId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PAYMENTMETHODID");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REMARK");

                    b.Property<decimal>("UserAccessId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("INCOME_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.IncomeType", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("status");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("typename");

                    b.HasKey("Id");

                    b.ToTable("IncomeType_tbl");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.MoreCapital", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("MoreDate")
                        .HasColumnType("DATE")
                        .HasColumnName("moredate");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("remark");

                    b.Property<decimal>("ToAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("toaccountid");

                    b.Property<string>("UserAccessId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("useraccessid");

                    b.HasKey("Id");

                    b.ToTable("MoreCapital_tbl");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.ToTable("USERS_TBL");
                });
#pragma warning restore 612, 618
        }
    }
}
