// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using POS_ASP_ORA.Data;

#nullable disable

namespace POS_ASP_ORA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304022300_AddGroupObject")]
    partial class AddGroupObject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS_ASP_ORA.Models.CashTransfer", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("AMOUNT");

                    b.Property<decimal>("FromAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("FROMACCOUNTID");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REMARK");

                    b.Property<decimal>("ToAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOACCOUNTID");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("TRANSFERDATE");

                    b.Property<decimal>("UserAccessId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("CASHTRANSFER_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Category", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORYNAME");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("CATEGORY_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Company", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COMPANYNAME");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("REMARK");

                    b.HasKey("Id");

                    b.ToTable("COMPANY_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.CustomerCheckin", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CheckinDate");

                    b.Property<decimal>("CustomerId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CustomerId");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("CustomerCheckin_tbl");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.ExpenseType", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TYPENAME");

                    b.HasKey("Id");

                    b.ToTable("EXPENSETYPE_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GroupID")
                        .HasColumnType("NUMBER")
                        .HasColumnName("GROUPID");

                    b.Property<decimal>("UserID")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.ToTable("GROUPMEMBER_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.GroupObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GroupID")
                        .HasColumnType("NUMBER")
                        .HasColumnName("GROUPID");

                    b.Property<decimal>("ObjectID")
                        .HasColumnType("NUMBER")
                        .HasColumnName("OBJECTID");

                    b.HasKey("Id");

                    b.ToTable("GROUPOBJECT_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Income", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("ComeDate")
                        .HasColumnType("DATE")
                        .HasColumnName("COMEDATE");

                    b.Property<decimal>("IncomeTypeId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("INCOMETYPEID");

                    b.Property<decimal>("PaymentMethodId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PAYMENTMETHODID");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REMARK");

                    b.Property<decimal>("UserAccessId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("INCOME_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.IncomeType", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("status");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("typename");

                    b.HasKey("Id");

                    b.ToTable("IncomeType_tbl");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.MoreCapital", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("MoreDate")
                        .HasColumnType("DATE")
                        .HasColumnName("moredate");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("remark");

                    b.Property<decimal>("ToAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("toaccountid");

                    b.Property<string>("UserAccessId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("useraccessid");

                    b.HasKey("Id");

                    b.ToTable("MoreCapital_tbl");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.ObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("OBJECTNAME");

                    b.HasKey("Id");

                    b.ToTable("OBJECT_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.OwnerDrawing", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("DrawingAmount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("DRAWINGAMOUNT");

                    b.Property<DateTime>("DrawingDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DRAWINGDATE");

                    b.Property<decimal>("FromAccountId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("FROMACCOUNTID");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REMARK");

                    b.Property<decimal>("UserAccessId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("OWNERDRAWING_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.PaymentMethod", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("METHODNAME");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("PAYMENTMETHOD_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Purchase", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BILLNO");

                    b.Property<decimal>("Discount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("DISCOUNT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("PURCHASEDATE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("SupplierId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("SUPPLIERID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("TOTALAMOUNT");

                    b.Property<decimal?>("UserAccessId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("PURCHASE_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.PurchasePayment", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("PayAmount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("PAYAMOUNT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("PAYMENTDATE");

                    b.Property<decimal>("PaymentMethod")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PAYMENTMETHOD");

                    b.Property<decimal>("PurchaseId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PURCHASEID");

                    b.HasKey("Id");

                    b.ToTable("PURCHASEPAYMENT_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CustomerId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CUSTOMERID");

                    b.Property<decimal>("Discount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("DISCOUNT");

                    b.Property<decimal>("InvoiceNo")
                        .HasColumnType("NUMBER")
                        .HasColumnName("INVOICENO");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("SALEDATE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("TOTALAMOUNT");

                    b.Property<decimal?>("UserAccessID")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERACCESSID");

                    b.HasKey("Id");

                    b.ToTable("SALE_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("COST");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("PRICE");

                    b.Property<decimal>("ProductId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PRODUCTID");

                    b.Property<decimal>("Qty")
                        .HasColumnType("NUMBER(18,3)")
                        .HasColumnName("QTY");

                    b.Property<decimal>("SaleId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("SALEID");

                    b.Property<decimal>("SubDiscount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("SUBDISCOUNT");

                    b.HasKey("Id");

                    b.ToTable("SALEDETAIL_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.SalePayment", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("PayAmount")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("PAYAMOUNT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("PAYMENTDATE");

                    b.Property<decimal>("PaymentMethod")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PAYMENTMETHOD");

                    b.Property<decimal>("SaleId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("SALEID");

                    b.HasKey("Id");

                    b.ToTable("SALEPAYMENT_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.UnitType", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("UNITTYPENAME");

                    b.HasKey("Id");

                    b.ToTable("UNITTYPE_TBL");
                });

            modelBuilder.Entity("POS_ASP_ORA.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.ToTable("USERS_TBL");
                });
#pragma warning restore 612, 618
        }
    }
}
